openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Line Manager Service'
servers:
  -
    url: 'http://localhost'
paths:
  '/rollingStock/{rollingStockId}':
    get:
      summary: 'Read a rolling stock'
      tags:
        - 'Rolling Stock'
      parameters:
        -
          $ref: '#/components/parameters/rollingStockId'
      responses:
        '200':
          description: 'Rolling stock found successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RollingStockDocument'
              example:
                type: emu
                class: '345'
                unitNumber: '3450001'
                manufacturer: Bombardier
                id: ybegUSCoMoZJh8NLdtXZRDJ6yny65hhH
                createdAt: 1570880557084
                updatedAt: 1570880557084
    put:
      summary: 'Update a rolling stock'
      tags:
        - 'Rolling Stock'
      parameters:
        -
          $ref: '#/components/parameters/rollingStockId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollingStockDocument'
            example:
              type: emu
              class: '345'
              unitNumber: '3450001'
              manufacturer: Bombardier
              id: ybegUSCoMoZJh8NLdtXZRDJ6yny65hhH
              createdAt: 1570880557084
              updatedAt: 1570880557084
      responses:
        '200':
          description: 'Rolling stock updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RollingStockDocument'
              example:
                type: emu
                class: '345'
                unitNumber: '3450001'
                manufacturer: Bombardier
                id: ybegUSCoMoZJh8NLdtXZRDJ6yny65hhH
                createdAt: 1570880557084
                updatedAt: 1570880557084
    delete:
      summary: 'Delete a rolling stock'
      tags:
        - 'Rolling Stock'
      parameters:
        -
          $ref: '#/components/parameters/rollingStockId'
      responses:
        '204':
          description: 'Rolling stock deleted successfully.'
  /rollingStock:
    post:
      summary: 'Create a rolling stock'
      tags:
        - 'Rolling Stock'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollingStockDocument'
            example:
              type: emu
              class: '345'
              unitNumber: '3450001'
              manufacturer: Bombardier
              id: ybegUSCoMoZJh8NLdtXZRDJ6yny65hhH
              createdAt: 1570880557084
              updatedAt: 1570880557084
      responses:
        '201':
          description: 'Created rolling stock successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RollingStockDocument'
              example:
                type: emu
                class: '345'
                unitNumber: '3450001'
                manufacturer: Bombardier
                id: ybegUSCoMoZJh8NLdtXZRDJ6yny65hhH
                createdAt: 1570880557084
                updatedAt: 1570880557084
    get:
      summary: 'List rolling stock'
      tags:
        - 'Rolling Stock'
      responses:
        '200':
          description: 'A paged array of rolling stock items.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RollingStockDocument'
              example:
                -
                  type: emu
                  class: '345'
                  unitNumber: '3450001'
                  manufacturer: Bombardier
                  id: ybegUSCoMoZJh8NLdtXZRDJ6yny65hhH
                  createdAt: 1570880557084
                  updatedAt: 1570880557084
components:
  parameters:
    rollingStockId:
      name: rollingStockId
      in: path
      required: true
      description: 'The ID of the rolling stock to retrieve'
      schema:
        type: string
  schemas:
    RollingStockDocument:
      additionalProperties: false
      required:
        - type
        - class
        - unitNumber
        - manufacturer
      properties:
        id:
          type: string
          readOnly: true
        createdAt:
          type: number
          readOnly: true
        updatedAt:
          type: number
          readOnly: true
        type:
          type: string
          enum:
            - diesel
            - electric
            - passenger
            - freight
            - maintenance
            - emu
            - dmu
        class:
          type: string
        unitNumber:
          type: string
        manufacturer:
          type: string
        manufactureDate:
          type: string
          format: date
        operator:
          type: string
        inService:
          type: boolean
        serviceStartDate:
          type: string
          format: date
        serviceEndDate:
          type: string
          format: date
  requestBodies: {}
